#%RAML 1.0 DataType

type: object
description: Represents a set of properties and its datatypes for AmericanFlight datatype
displayName: American Flight
properties:
  ID?: integer
  airlineName: string
  price: number
  emptySeats: integer
  code: string
  origin: string
  destination: string
  departureDate: string
  plane:
    type: object
    properties:
      type?: string
      totalSeats?: integer  
