#%RAML 1.0 NamedExample

value:
  airlineName: American Airlines
  price: 541
  emptySeats: 0
  code: rree0001
  origin: MUA
  destination: LAX
  departureDate: 2016-01-20T00:00:00
  plane:
    type: Boeing 787
    totalSeats: 200